# Basics
# baseURL: /
title: Platform.sh Documentation
author: Platform.sh
description: Platform.sh User Documentation

# Themes
theme: psh-docs
themesdir: '../../themes'

timeout: 60s

uglyurls: true
pygmentsUseClasses: true

# Language settings
languages:
  en:
    languageName: English
    weight: 10

disableKinds: ["taxonomy"]

baseURL: "https://docs.platform.sh"

summaryLength: 3

outputs:
    home:
      - HTML
      - JSON
      - RSS
      - devcenter
    section:
      - HTML
      - RSS

outputFormats:
  devcenter:
    mediaType: "application/json"
    baseName: "json/devcenter"
    isPlainText: true

# Math typesetting as per 0.125.0 - https://gohugo.io/content-management/mathematics/
markup:
    goldmark:
        renderer:
            unsafe: true
    # goldmark:
        extensions:
            passthrough:
                delimiters:
                    block:
                    - - \[
                      - \]
                    - - $$
                      - $$
                    inline:
                    - - \(
                      - \)
            enable: true
params:
    math: true

module:
    mounts:
        - source: "node_modules/mermaid/dist"
          target: "static/mermaid"
        - source: "node_modules/asciinema-player/dist/bundle"
          target: "static/asciinema"
        - source: "node_modules/alpinejs/dist"
          target: "static/alpinejs"

        - source: "../../shared/data"
          target: "data"

        - source: "src"
          target: "content"

          lang: "en"
        - source: "static"
          target: "static"


security:
  funcs:
    getenv:
    - ^GITHUB_
    - ^HUGO_HEAP_ID
  http:
    methods:
    - GET
