
# Basics
version: "1.1.0"
description: Platform.sh User Documentation
author: Platform.sh
title: User documentation
issuerepo: "https://github.com/platformsh/platformsh-docs/"
repo: "https://github.com/platformsh/platformsh-docs/"
folder: "sites/platform"
editPageButton: true

# Vendorization
vendor:
    name: Platform.sh
    cli: platform
    altname: platformsh
    env_prefix: PLATFORM
    cli_prefix: PLATFORMSH
    recruit:
        active: true
        link: https://auth.api.platform.sh/register/
        cta: Activate your trial
        title: Try for 30 days
        description: "Flexible, version-controlled infrastructure provisioning and development-to-production workflows"
    config:
        version: 1
        dir: .platform
        filename: applications.yaml
        files:
            routes: .platform/routes.yaml
            services: .platform/services.yaml
            app: .platform.app.yaml
            apps: .platform/applications.yaml
        prefix:
            apps: applications
            services: services
            routes: routes
    urls:
        main: https://platform.sh/
        docs: https://docs.platform.sh/
        support: https://support.platform.sh/
        sales: https://platform.sh/contact
        console: https://console.platform.sh/
        api: https://api.platform.sh/
        host: platform.sh
        hostname: platformsh.site
        register: https://auth.api.platform.sh/register

# Images (kept in static/)
logo: "images/logos/Platformsh_logo_white.svg"
logolinksto: "/"
logoAlt: "Platform.sh"
favicon: "images/logos/favicon.ico"

gtm: "GTM-KRPJGT4"

# Actions in main header
headerActions:
  headerActionPrimary:
    destination: https://auth.api.platform.sh/register
    linkText: Sign up
  headerActionSecondary:
    destination: https://console.platform.sh/
    linkText: Log in

# Search
rank: 1
site: docs
# Don't include trailing slash. It's just easier that way.
rooturl: "https://docs.platform.sh"

# 404
_404:
  title: "Lost in space"
  image: "/images/404/404-8.png"
  issues: "https://github.com/platformsh/platformsh-docs/issues/new"

# Sections in the navigation sidebar
navSections:
  get-started:
    title: Get started
    section: get-started
    weight: -120
  learn:
    title: Learn
    section: learn
    weight: -110
  guides:
    title: Frameworks
    section: guides
    weight: -100
  home:
    title: Reference
    section: home
    weight: -90

nonDocsSections:
  apidocs:
    title: API Documentation
    link: https://api.platform.sh/docs
    weight: -80
  # community:
  #   title: Community Forum
  #   link: https://community.platform.sh
  #   weight: -70

# Metadata
meta:
  sitename: "Platform.sh User Documentation"
  description: Platform.sh is a second-generation Platform-as-a-Service built especially for continuous deployment. It allows you to host web applications on the cloud while making your development and testing workflows more productive.
  image: "https://docs.platform.sh/images/logos/docs_social_2021.jpg"
  url: "https://docs.platform.sh"
  twittercard:
    card: "summary_large_image"
    site: "@platformsh"
    title: "Platform.sh User Documentation"
    description: "Platform.sh is a second-generation Platform-as-a-Service built especially for continuous deployment. It allows you to host web applications on the cloud while making your development and testing workflows more productive."
    creator: "@platformsh"
    image: "https://docs.platform.sh/images/logos/docs_social_2021.jpg"
  keywords:
    - PaaS
    - cloud hosting
    - DevOps
    - PHP
    - Node.js
    - Go
    - Golang
    - Python
    - .NET
    - Ruby
    - Java
    - Drupal
    - Wordpress
    - Symfony
    - Maven
    - Lisp
    - Hibernate
    - Jakarta
    - Spring
    - TYPO3
